@startuml "identity-chaining-flow"
hide footbox
skinparam {
    sequenceParticipantBorderThickness 0
}

participant ASa as "Authorization\nServer\nDomain A"
participant client as "Actor\n(Domain A)"
participant ASb as "Authorization\nServer\nDomain B"
participant pr as "Protected\nResource\nDomain B"

client -> client: (A) discover\nAuthorization\nServer\nDomain B

client -> ASa: (B) exchange token\n[RFC 8693]
return (C) <authorization grant>

client -> ASb: (D) perform asseration\n[RFC 7521]
return (E) <access token>

client -> pr: (F) access



@enduml